# --- Estágio de Build ---
# Usamos uma imagem Node completa para instalar dependências e construir o projeto
FROM node:18-alpine AS builder

# Define o diretório de trabalho
WORKDIR /usr/src/app

# Copia os arquivos de definição de dependências e instala
COPY package*.json ./
RUN npm install

# Copia todo o código-fonte
COPY . .

# Compila o TypeScript para JavaScript
RUN npm run build

# --- Estágio de Produção ---
# Agora, usamos uma imagem Node mais leve, apenas para rodar o código compilado
FROM node:18-alpine

WORKDIR /usr/src/app

# Copia apenas as dependências de produção do estágio de build
COPY --from=builder /usr/src/app/package*.json ./
RUN npm ci --only=production

# Copia o código já compilado do estágio de build
COPY --from=builder /usr/src/app/dist ./dist

# Expõe a porta que o Nest.js usa por padrão
EXPOSE 3000

# O comando para iniciar a aplicação em modo de produção
CMD ["node", "dist/main"]